version: '3.8'
services:
   web:
       build: .
       command: bash -c "python src/preprocess.py && python src/train.py && python src/predict.py -m LOG_REG -t func"
       ports:
           - 8000:8000
       image: altairzero/mle-template:latest